version: "3.9"
services:
  spring-boot-marvel:
    container_name: spring-boot-marvel
    build:
      context: .
      dockerfile: ./spring-boot-marvel/Dockerfile
    networks:
      - proxynet
    environment:
      SERVICE_PORT: 8080
    ports:
      - "8080:8080"

networks:
  proxynet:
    name: spring-boot-marvel-network
